window.RENDERLESS_BOOTSTRAP = {
  supportedDimensions: ['1920x1080', '1080x1920', '1080x1080', '1080x1350'],
  brandedAssets: [
    { id: 1, name: 'red-sox-scorebug-1920x1080.png', folder: 'Scorebugs', dimension: '1920x1080', createdAt: new Date('2026-01-10T09:10:00').toISOString(), src: 'https://dummyimage.com/1920x1080/0f172a/93c5fd.png&text=Scorebug+16:9' },
    { id: 2, name: 'yankees-story-1080x1920.png', folder: 'Social Stories', dimension: '1080x1920', createdAt: new Date('2026-01-14T12:45:00').toISOString(), src: 'https://dummyimage.com/1080x1920/111827/86efac.png&text=Story+9:16' },
    { id: 3, name: 'postgame-square-1080x1080.png', folder: 'Social Square', dimension: '1080x1080', createdAt: new Date('2026-01-16T18:25:00').toISOString(), src: 'https://dummyimage.com/1080x1080/1e293b/fca5a5.png&text=Square+1:1' },
    { id: 4, name: 'lineup-feed-1080x1350.png', folder: 'Social Feed', dimension: '1080x1350', createdAt: new Date('2026-01-18T08:00:00').toISOString(), src: 'https://dummyimage.com/1080x1350/172554/bae6fd.png&text=Feed+4:5' },
  ],
  initialGameState: {
    matchup: 'Red Sox vs Yankees',
    inning: 1,
    inningState: 'Top',
    score: { BOS: 0, NYY: 0 },
    balls: 0,
    strikes: 0,
    outs: 0,
    runnersOnBase: 'Bases empty',
    pitcher: 'Brayan Bello',
    batter: 'Anthony Volpe',
    pitchType: '4-Seam Fastball',
    pitchVelocity: 96,
    pitchLocation: 'Outer third',
    batSpeed: 0,
    exitVelocity: 0,
    launchAngle: 0,
    projectedDistance: 0,
    lastEvent: 'Waiting to start MLB simulation.',
  },
  mlbSimulationFeed: [
    { inning: 1, inningState: 'Top', summary: 'Pitch 1: Ball low to Volpe.', score: { BOS: 0, NYY: 0 }, count: { balls: 1, strikes: 0, outs: 0 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Anthony Volpe', pitch: { type: '4-Seam Fastball', velocity: 96, location: 'Low and away' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 1, inningState: 'Top', summary: 'Pitch 2: Called strike.', score: { BOS: 0, NYY: 0 }, count: { balls: 1, strikes: 1, outs: 0 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Anthony Volpe', pitch: { type: 'Sinker', velocity: 95, location: 'Inner edge' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 1, inningState: 'Top', summary: 'Pitch 3: Foul ball.', score: { BOS: 0, NYY: 0 }, count: { balls: 1, strikes: 2, outs: 0 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Anthony Volpe', pitch: { type: 'Slider', velocity: 86, location: 'Down and in' }, hit: { batSpeed: 70, exitVelocity: 82, launchAngle: 29, projectedDistance: 214 } },
    { inning: 1, inningState: 'Top', summary: 'Pitch 4: Volpe takes ball four and walks.', score: { BOS: 0, NYY: 0 }, count: { balls: 4, strikes: 2, outs: 0 }, runnersOnBase: 'Runner on 1st', pitcher: 'Brayan Bello', batter: 'Anthony Volpe', pitch: { type: 'Changeup', velocity: 87, location: 'Off plate away' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 1, inningState: 'Top', summary: 'Pitch 5: Soto swings through strike three. One out.', score: { BOS: 0, NYY: 0 }, count: { balls: 1, strikes: 3, outs: 1 }, runnersOnBase: 'Runner on 1st', pitcher: 'Brayan Bello', batter: 'Juan Soto', pitch: { type: 'Changeup', velocity: 89, location: 'Bottom edge' }, hit: { batSpeed: 74, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 1, inningState: 'Top', summary: 'Pitch 6: Judge puts it in play for a deep fly out. Two outs.', score: { BOS: 0, NYY: 0 }, count: { balls: 0, strikes: 1, outs: 2 }, runnersOnBase: 'Runner on 1st', pitcher: 'Brayan Bello', batter: 'Aaron Judge', pitch: { type: '4-Seam Fastball', velocity: 97, location: 'Middle-up' }, hit: { batSpeed: 81, exitVelocity: 103, launchAngle: 34, projectedDistance: 360 } },
    { inning: 1, inningState: 'Top', summary: 'Pitch 7: Stanton grounds out to short. Side retired.', score: { BOS: 0, NYY: 0 }, count: { balls: 1, strikes: 1, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Giancarlo Stanton', pitch: { type: 'Sinker', velocity: 95, location: 'Low-middle' }, hit: { batSpeed: 76, exitVelocity: 92, launchAngle: -6, projectedDistance: 58 } },

    { inning: 1, inningState: 'Bottom', summary: 'Pitch 8: Duran singles on a line drive.', score: { BOS: 0, NYY: 0 }, count: { balls: 1, strikes: 1, outs: 0 }, runnersOnBase: 'Runner on 1st', pitcher: 'Gerrit Cole', batter: 'Jarren Duran', pitch: { type: '4-Seam Fastball', velocity: 98, location: 'Outer third' }, hit: { batSpeed: 78, exitVelocity: 101, launchAngle: 11, projectedDistance: 196 } },
    { inning: 1, inningState: 'Bottom', summary: 'Pitch 9: Devers works a full count walk.', score: { BOS: 0, NYY: 0 }, count: { balls: 4, strikes: 2, outs: 0 }, runnersOnBase: 'Runners on 1st and 2nd', pitcher: 'Gerrit Cole', batter: 'Rafael Devers', pitch: { type: 'Slider', velocity: 88, location: 'Outside' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 1, inningState: 'Bottom', summary: 'Pitch 10: Story lines an RBI single. Red Sox lead 1-0.', score: { BOS: 1, NYY: 0 }, count: { balls: 1, strikes: 0, outs: 0 }, runnersOnBase: 'Runners on 1st and 2nd', pitcher: 'Gerrit Cole', batter: 'Trevor Story', pitch: { type: 'Cutter', velocity: 92, location: 'Inner edge' }, hit: { batSpeed: 79, exitVelocity: 105, launchAngle: 12, projectedDistance: 212 } },
    { inning: 1, inningState: 'Bottom', summary: 'Pitch 11: Casas strikes out swinging. One out.', score: { BOS: 1, NYY: 0 }, count: { balls: 2, strikes: 3, outs: 1 }, runnersOnBase: 'Runners on 1st and 2nd', pitcher: 'Gerrit Cole', batter: 'Triston Casas', pitch: { type: 'Knuckle Curve', velocity: 82, location: 'Below zone' }, hit: { batSpeed: 71, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 1, inningState: 'Bottom', summary: 'Pitch 12: Yoshida taps a grounder; force at second. Two outs.', score: { BOS: 1, NYY: 0 }, count: { balls: 0, strikes: 1, outs: 2 }, runnersOnBase: 'Runners on 1st and 3rd', pitcher: 'Gerrit Cole', batter: 'Masataka Yoshida', pitch: { type: '4-Seam Fastball', velocity: 97, location: 'Low-in' }, hit: { batSpeed: 68, exitVelocity: 81, launchAngle: -8, projectedDistance: 52 } },
    { inning: 1, inningState: 'Bottom', summary: 'Pitch 13: Abreu grounds out; inning over.', score: { BOS: 1, NYY: 0 }, count: { balls: 1, strikes: 1, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Gerrit Cole', batter: 'Wilyer Abreu', pitch: { type: 'Changeup', velocity: 86, location: 'Outer knee' }, hit: { batSpeed: 73, exitVelocity: 87, launchAngle: -2, projectedDistance: 64 } },

    { inning: 2, inningState: 'Top', summary: 'Pitch 14: Torres doubles down the line.', score: { BOS: 1, NYY: 0 }, count: { balls: 1, strikes: 0, outs: 0 }, runnersOnBase: 'Runner on 2nd', pitcher: 'Brayan Bello', batter: 'Gleyber Torres', pitch: { type: 'Sinker', velocity: 95, location: 'Middle-in' }, hit: { batSpeed: 77, exitVelocity: 102, launchAngle: 17, projectedDistance: 276 } },
    { inning: 2, inningState: 'Top', summary: 'Pitch 15: Verdugo hits a sacrifice fly; game tied 1-1.', score: { BOS: 1, NYY: 1 }, count: { balls: 0, strikes: 1, outs: 1 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Alex Verdugo', pitch: { type: 'Changeup', velocity: 88, location: 'Middle' }, hit: { batSpeed: 74, exitVelocity: 96, launchAngle: 31, projectedDistance: 301 } },
    { inning: 2, inningState: 'Top', summary: 'Pitch 16: Wells strikes out looking. Two outs.', score: { BOS: 1, NYY: 1 }, count: { balls: 1, strikes: 3, outs: 2 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Austin Wells', pitch: { type: 'Slider', velocity: 85, location: 'Outer black' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 2, inningState: 'Top', summary: 'Pitch 17: Volpe flies out to right. Inning over.', score: { BOS: 1, NYY: 1 }, count: { balls: 2, strikes: 1, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Anthony Volpe', pitch: { type: '4-Seam Fastball', velocity: 96, location: 'High middle' }, hit: { batSpeed: 75, exitVelocity: 91, launchAngle: 30, projectedDistance: 287 } },

    { inning: 2, inningState: 'Bottom', summary: 'Pitch 18: Duran triples to right-center.', score: { BOS: 1, NYY: 1 }, count: { balls: 0, strikes: 1, outs: 0 }, runnersOnBase: 'Runner on 3rd', pitcher: 'Gerrit Cole', batter: 'Jarren Duran', pitch: { type: '4-Seam Fastball', velocity: 98, location: 'Middle-middle' }, hit: { batSpeed: 80, exitVelocity: 107, launchAngle: 20, projectedDistance: 360 } },
    { inning: 2, inningState: 'Bottom', summary: 'Pitch 19: Devers singles home Duran. Red Sox lead 2-1.', score: { BOS: 2, NYY: 1 }, count: { balls: 1, strikes: 1, outs: 0 }, runnersOnBase: 'Runner on 1st', pitcher: 'Gerrit Cole', batter: 'Rafael Devers', pitch: { type: 'Cutter', velocity: 92, location: 'Inner half' }, hit: { batSpeed: 79, exitVelocity: 104, launchAngle: 10, projectedDistance: 198 } },
    { inning: 2, inningState: 'Bottom', summary: 'Pitch 20: Story grounds into double play. Two outs.', score: { BOS: 2, NYY: 1 }, count: { balls: 0, strikes: 1, outs: 2 }, runnersOnBase: 'Bases empty', pitcher: 'Gerrit Cole', batter: 'Trevor Story', pitch: { type: 'Sinker', velocity: 95, location: 'Low-in' }, hit: { batSpeed: 76, exitVelocity: 90, launchAngle: -9, projectedDistance: 56 } },
    { inning: 2, inningState: 'Bottom', summary: 'Pitch 21: Casas draws ball four.', score: { BOS: 2, NYY: 1 }, count: { balls: 4, strikes: 2, outs: 2 }, runnersOnBase: 'Runner on 1st', pitcher: 'Gerrit Cole', batter: 'Triston Casas', pitch: { type: 'Slider', velocity: 87, location: 'Off plate' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 2, inningState: 'Bottom', summary: 'Pitch 22: Yoshida strikes out swinging. End of 2nd.', score: { BOS: 2, NYY: 1 }, count: { balls: 1, strikes: 3, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Gerrit Cole', batter: 'Masataka Yoshida', pitch: { type: 'Knuckle Curve', velocity: 81, location: 'Below zone' }, hit: { batSpeed: 70, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
  ],
};
