window.RENDERLESS_BOOTSTRAP = {
  supportedDimensions: ['1920x1080', '1080x1920', '1080x1080', '1080x1350'],
  brandedAssets: [
    { id: 1, name: 'red-sox-scorebug-1920x1080.png', folder: 'Scorebugs', dimension: '1920x1080', createdAt: new Date('2026-01-10T09:10:00').toISOString(), src: 'https://dummyimage.com/1920x1080/0f172a/93c5fd.png&text=Scorebug+16:9' },
    { id: 2, name: 'yankees-story-1080x1920.png', folder: 'Social Stories', dimension: '1080x1920', createdAt: new Date('2026-01-14T12:45:00').toISOString(), src: 'https://dummyimage.com/1080x1920/111827/86efac.png&text=Story+9:16' },
    { id: 3, name: 'postgame-square-1080x1080.png', folder: 'Social Square', dimension: '1080x1080', createdAt: new Date('2026-01-16T18:25:00').toISOString(), src: 'https://dummyimage.com/1080x1080/1e293b/fca5a5.png&text=Square+1:1' },
    { id: 4, name: 'lineup-feed-1080x1350.png', folder: 'Social Feed', dimension: '1080x1350', createdAt: new Date('2026-01-18T08:00:00').toISOString(), src: 'https://dummyimage.com/1080x1350/172554/bae6fd.png&text=Feed+4:5' },
  ],
  initialGameState: {
    matchup: 'Red Sox vs Yankees',
    inning: 1,
    inningState: 'Top',
    score: { BOS: 0, NYY: 0 },
    balls: 0,
    strikes: 0,
    outs: 0,
    runnersOnBase: 'Bases empty',
    pitcher: 'Brayan Bello',
    batter: 'Anthony Volpe',
    pitchType: '4-Seam Fastball',
    pitchVelocity: 96,
    pitchLocation: 'Outer third',
    batSpeed: 0,
    exitVelocity: 0,
    launchAngle: 0,
    projectedDistance: 0,
    lastEvent: 'Waiting to start MLB simulation.',
  },
  mlbSimulationFeed: [
    { inning: 1, inningState: 'Top', summary: 'Volpe singles to center to open the game.', score: { BOS: 0, NYY: 0 }, count: { balls: 1, strikes: 1, outs: 0 }, runnersOnBase: 'Runner on 1st', pitcher: 'Brayan Bello', batter: 'Anthony Volpe', pitch: { type: '4-Seam Fastball', velocity: 96, location: 'Outer third' }, hit: { batSpeed: 73, exitVelocity: 97, launchAngle: 9, projectedDistance: 168 } },
    { inning: 1, inningState: 'Top', summary: 'Soto grounds into a force play; Yankees threaten but do not score.', score: { BOS: 0, NYY: 0 }, count: { balls: 2, strikes: 1, outs: 2 }, runnersOnBase: 'Runner on 1st', pitcher: 'Brayan Bello', batter: 'Juan Soto', pitch: { type: 'Sinker', velocity: 95, location: 'Inside corner' }, hit: { batSpeed: 71, exitVelocity: 88, launchAngle: -4, projectedDistance: 64 } },
    { inning: 1, inningState: 'Bottom', summary: 'Duran scores on a Devers RBI single. Boston leads 1-0.', score: { BOS: 1, NYY: 0 }, count: { balls: 2, strikes: 2, outs: 1 }, runnersOnBase: 'Runner on 1st', pitcher: 'Gerrit Cole', batter: 'Rafael Devers', pitch: { type: 'Slider', velocity: 88, location: 'Middle-away' }, hit: { batSpeed: 77, exitVelocity: 101, launchAngle: 12, projectedDistance: 221 } },
    { inning: 2, inningState: 'Top', summary: 'Judge works a walk and Stanton follows with an RBI double. Tied 1-1.', score: { BOS: 1, NYY: 1 }, count: { balls: 3, strikes: 1, outs: 1 }, runnersOnBase: 'Runner on 2nd', pitcher: 'Brayan Bello', batter: 'Giancarlo Stanton', pitch: { type: 'Changeup', velocity: 87, location: 'Low-middle' }, hit: { batSpeed: 75, exitVelocity: 103, launchAngle: 16, projectedDistance: 278 } },
    { inning: 2, inningState: 'Bottom', summary: 'Casas lifts a sac fly and Boston regains the lead 2-1.', score: { BOS: 2, NYY: 1 }, count: { balls: 1, strikes: 2, outs: 2 }, runnersOnBase: 'Bases empty', pitcher: 'Gerrit Cole', batter: 'Triston Casas', pitch: { type: 'Cutter', velocity: 92, location: 'Upper zone' }, hit: { batSpeed: 72, exitVelocity: 94, launchAngle: 37, projectedDistance: 286 } },
    { inning: 3, inningState: 'Top', summary: 'Yankees put two on but Bello strands both with a strikeout.', score: { BOS: 2, NYY: 1 }, count: { balls: 0, strikes: 2, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Anthony Rizzo', pitch: { type: 'Slider', velocity: 86, location: 'Back foot' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 3, inningState: 'Bottom', summary: 'Yoshida singles home a run. Boston extends to 3-1.', score: { BOS: 3, NYY: 1 }, count: { balls: 1, strikes: 1, outs: 2 }, runnersOnBase: 'Runner on 1st', pitcher: 'Gerrit Cole', batter: 'Masataka Yoshida', pitch: { type: '4-Seam Fastball', velocity: 97, location: 'Outer edge' }, hit: { batSpeed: 74, exitVelocity: 99, launchAngle: 8, projectedDistance: 183 } },
    { inning: 4, inningState: 'Top', summary: 'Torres lines an RBI single. Boston leads 3-2.', score: { BOS: 3, NYY: 2 }, count: { balls: 2, strikes: 1, outs: 1 }, runnersOnBase: 'Runner on 1st', pitcher: 'Brayan Bello', batter: 'Gleyber Torres', pitch: { type: 'Sinker', velocity: 94, location: 'Middle-in' }, hit: { batSpeed: 76, exitVelocity: 100, launchAngle: 11, projectedDistance: 206 } },
    { inning: 4, inningState: 'Bottom', summary: 'No damage in the 4th for either side after a double-play ball.', score: { BOS: 3, NYY: 2 }, count: { balls: 1, strikes: 0, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Gerrit Cole', batter: 'Trevor Story', pitch: { type: 'Slider', velocity: 87, location: 'Bottom edge' }, hit: { batSpeed: 70, exitVelocity: 89, launchAngle: -6, projectedDistance: 72 } },
    { inning: 5, inningState: 'Top', summary: 'Judge ties it with a solo homer to left-center. 3-3 game.', score: { BOS: 3, NYY: 3 }, count: { balls: 2, strikes: 1, outs: 0 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Aaron Judge', pitch: { type: '4-Seam Fastball', velocity: 97, location: 'Middle-up' }, hit: { batSpeed: 82, exitVelocity: 110, launchAngle: 28, projectedDistance: 425 } },
    { inning: 5, inningState: 'Bottom', summary: 'Devers answers with an RBI double. Boston up 4-3.', score: { BOS: 4, NYY: 3 }, count: { balls: 1, strikes: 2, outs: 1 }, runnersOnBase: 'Runner on 2nd', pitcher: 'Gerrit Cole', batter: 'Rafael Devers', pitch: { type: 'Cutter', velocity: 91, location: 'Inner half' }, hit: { batSpeed: 79, exitVelocity: 105, launchAngle: 17, projectedDistance: 302 } },
    { inning: 6, inningState: 'Top', summary: 'A quiet top half keeps Boston ahead 4-3.', score: { BOS: 4, NYY: 3 }, count: { balls: 0, strikes: 2, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Brayan Bello', batter: 'Giancarlo Stanton', pitch: { type: 'Changeup', velocity: 88, location: 'Below zone' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 6, inningState: 'Bottom', summary: 'Abreu singles home one. Boston leads 5-3.', score: { BOS: 5, NYY: 3 }, count: { balls: 2, strikes: 2, outs: 2 }, runnersOnBase: 'Runner on 1st', pitcher: 'Clay Holmes', batter: 'Wilyer Abreu', pitch: { type: 'Sinker', velocity: 95, location: 'Outer knee' }, hit: { batSpeed: 74, exitVelocity: 98, launchAngle: 10, projectedDistance: 190 } },
    { inning: 7, inningState: 'Top', summary: 'LeMahieu plates one with a groundout. Boston 5-4.', score: { BOS: 5, NYY: 4 }, count: { balls: 0, strikes: 1, outs: 2 }, runnersOnBase: 'Bases empty', pitcher: 'Chris Martin', batter: 'DJ LeMahieu', pitch: { type: 'Cutter', velocity: 92, location: 'Inner edge' }, hit: { batSpeed: 69, exitVelocity: 84, launchAngle: -2, projectedDistance: 58 } },
    { inning: 7, inningState: 'Bottom', summary: 'Boston is retired in order; still 5-4.', score: { BOS: 5, NYY: 4 }, count: { balls: 1, strikes: 2, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Tommy Kahnle', batter: 'Connor Wong', pitch: { type: 'Changeup', velocity: 84, location: 'Low-away' }, hit: { batSpeed: 67, exitVelocity: 82, launchAngle: 44, projectedDistance: 233 } },
    { inning: 8, inningState: 'Top', summary: 'Torres reaches, but Boston escapes with a strikeout to end the inning.', score: { BOS: 5, NYY: 4 }, count: { balls: 1, strikes: 2, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Kenley Jansen', batter: 'Anthony Rizzo', pitch: { type: 'Cutter', velocity: 93, location: 'Outer black' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
    { inning: 8, inningState: 'Bottom', summary: 'Duran steals second and scores on a Story single. Boston 6-4.', score: { BOS: 6, NYY: 4 }, count: { balls: 2, strikes: 1, outs: 1 }, runnersOnBase: 'Runner on 1st', pitcher: 'Luke Weaver', batter: 'Trevor Story', pitch: { type: '4-Seam Fastball', velocity: 95, location: 'Middle-middle' }, hit: { batSpeed: 78, exitVelocity: 104, launchAngle: 13, projectedDistance: 244 } },
    { inning: 9, inningState: 'Top', summary: 'Jansen closes it out with a strikeout. Final: Red Sox 6, Yankees 4.', score: { BOS: 6, NYY: 4 }, count: { balls: 1, strikes: 2, outs: 3 }, runnersOnBase: 'Bases empty', pitcher: 'Kenley Jansen', batter: 'Aaron Judge', pitch: { type: 'Cutter', velocity: 94, location: 'Outer edge' }, hit: { batSpeed: 0, exitVelocity: 0, launchAngle: 0, projectedDistance: 0 } },
  ],
};
